### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/load-json-file#23]
Would be nice if this had 0 dependencies:

```js
import {readFileSync} from 'node:fs';
import {readFile} from 'node:fs/promises';

const parse = (uint8, options = {}) => {
  // unlike buf.toString('utf8') or or readFile(path, 'utf8'), TextDecoder will remove BOM
  let data = new TextDecoder().decode(uint8);

  if (typeof options.beforeParse === 'function') {
    data = options.beforeParse(data);
  }

  return JSON.parse(data, options.reviver);
};

export const loadJsonFile = (filePath, options) =>
  readFile(filePath).then(data => parse(data, options));

export const loadJsonFileSync = (filePath, options) =>
  parse(readFileSync(filePath), options);
```

**Comment by sindresorhus** [comment]
Yeah, we could probably reduce the dependencies. `graceful-fs` was useful in the past, but it's too hacky and less useful these days. `parse-json` would probably stay though as it improves JSON errors. I'll work on ESMifying this package later today.

Sidenote: I really wish Node.js had a `fs.readJson` built-in method with good JSON errors, since it's such a common use-case. Maybe you should open an issue about that on the Node.js issue tracker. This kinda basic stuff should really be built-in.

**Comment by jimmywarting** [comment]
that could maybe change with the (dynamic) "import json" proposal

**Comment by jimmywarting** [comment]
one new additions that arrived into node was [stream-consumers](https://www.npmjs.com/package/stream-consumers).
among it was `json(iterable).then(console.log)`

the idea came from fetch's `response.json()` so it should strip BOM also i guess
so you could do: `await json(fs.createReadStream(path))`

but this is only async, there is no sync alternative, and gives even worse error

**Comment by sindresorhus** [comment]
> that could maybe change with the (dynamic) "import json" proposal

Importing JSON and reading JSON are different. Importing has overhead and also caches. Reading directly from disk will always be faster.

**Comment by sindresorhus** [comment]
I ended up dropping `parse-json`. Not worth the bloat.

https://github.com/sindresorhus/load-json-file/releases/tag/v7.0.0

**Comment by jimmywarting** [comment]
Thx
